import Head from 'next/head';
import Experiences from '../components/Experiences';

export default function WorkExperience(): JSX.Element {

    return (
        <div>
            <Head>
                <title>Pradeep Kumar Medam - Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Experiences/>
        </div>
    );
}
